server:
  shutdown: graceful
  port: 8080

spring:
  config:
    import:
      - security/application-db.yml
      - security/application-security.yml
      - security/application-mail.yml
      - security/application-s3.yml
      - application-file.yml
  data:
    web:
      pageable:
        one-indexed-parameters:
          true

  profiles:
    active: local
file:
  dir: classpath:files/

